@startuml capture_activity

start

partition Initialization {
  :open device and start camera;
  :create a body tracker;
  :setup pipe or shared memory;
}

partition Running {
  while (application running) is (yes)
    :get a sensor capture;
    :enqueue capture;
    note right
      Captures are processed asyncronously
      from the input queue to produce body
      tracking results.
    end note
    :release sensor capture;
    :pop body frame results;
    note right
      A timeout value can be set to determine
      how long to wait for results from the
      output queue (or infinity to wait forever).
    end note
    :send body frame results to classifier program;
    :release body frame;
  endwhile (no)
}

partition Cleanup {
  :destroy infrastructure for IPC with classifier program;
  :shut down body tracker;
  :stop cameras and close device;
}

stop

@enduml