'''
    Server Client Request and Response ID's
'''
ERROR_RESPONSE_ID = 0xFF
START_REQUEST_ID = 0x02
START_RESPONSE_ID = 0x03
STOP_REQUEST_ID = 0x00
STOP_RESPONSE_ID = 0x01
SET_DCONFIG_REQUEST_ID = 0x05
SET_DCONFIG_RESPONSE_ID = 0x06
GET_DCONFIG_REQUEST_ID = 0x0A
GET_DCONFIG_RESPONSE_ID = 0x0B
GET_DINTRIN_REQUEST_ID = 0x0F
GET_DINTRIN_RESPONSE_ID = 0x10
GET_DINFO_REQUEST_ID = 0x14
GET_DINFO_RESPONSE_ID = 0x15
CAP_FRAME_REQUEST_ID = 0x19
CAP_FRAME_RESPONSE_ID = 0x1A

'''
    Device Constants
'''
DEVICE0 = 0
DEVICE1 = 1

'''
    Buffer Type Constants
'''
COLOR_BUFF_TYPE = '0'
PCM_BUFF_TYPE = '1'
DEPTH_BUFF_TYPE = '2'
'''
    Return Data Processing Constants
'''
SUCCESS = 0
ERROR = 1
INFO = 1
DATA = 2
FRAMES = 1
COLOR_DATA = 0
PCM_DATA = 1
DEPTH_DATA = 1

'''
    Exit Procedure Constants
'''
STOP_DEVICE = 1
NO_STOP_DEVICE = 0
